server:
  port: 8081

spring:
  application.name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: "http://localhost:8282/realms/sadovod"
            user-name-attribute: preferred_username

        registration:
          keycloak:
            client-id: sadovod-app
            client-secret: FHTqC6rjlevSs3iHL7kLgXQiZlSyJ02i
            scope:
              - openid
              - view_suppliers
              - add_supplier
              - update_supplier
              - microprofile-jwt
            authorization-grant-type: authorization_code



#  security:
#    oauth2:
#      client:
#        registration:
#          gateway:
#            provider: keycloak
#            client-id: sadovod-user-service
#            client-secret: C9hmye4U49rlJXOD9Pv9uE2W7ks8XTlH
#            client-name: user-service
#            authorization-grant-type: authorization_code
#            redirect-uri: "http://localhost:8081/login/oauth2/code/{registrationId}"
#            scope:
#              - openid
#              - supplier_create
#              - supplier_read
#              - supplier_update
#        provider:
#          keycloak:
#            issuer-uri: "http://localhost:8282/realms/sadovod"
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
