server:
  port: 8080

spring:
  application.name: gateway-service
  config:
    import: optional:configserver:http://localhost:8888

  security:
    oauth2:
      client:
        registration:
          gateway:
            provider: spring
            client-id: oidc-client
            client-secret: secret
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8080/login/oauth2/code/{registrationId}"
            scope: openid, profile
        provider:
          spring:
            issuer-uri: http://127.0.0.1:8081
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
