spring:
  application:
    name: ua-service

  devtools:
    restart:
      poll-interval: 2s
      quiet-period: 1s

  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/supplier-service
    username: postgres
    password: postgres
    hikari:
      auto-commit: true
      schema: app

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
server:
  port: 7414
