global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: "audit-service-app"
    scrape_interval: 5s
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['host.docker.internal:8094']
