server:
  port: 0
spring:
  application:
    name: supplier-service
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/supplier-service
    username: postgres
    password: postgres
    hikari:
      auto-commit: true
      schema: app

  config:
    import: optional:configserver:http://localhost:8888
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/sadovod
  jackson:
    property-naming-strategy: SNAKE_CASE
    default-property-inclusion: non_null

eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true





