
spring:

  # jackson config
  jackson:
    serialization:
      write-dates-as-timestamps: false
      write-enums-using-to-string: false
    property-naming-strategy: SNAKE_CASE

  # datasource config
  datasource:
    hikari:
      schema: application
      driver-class-name: org.postgresql.Driver
      username: postgres
      password: postgres
      auto-commit: true
      maximum-pool-size: 20
    url: jdbc:postgresql://localhost:5432/sadovnik

  # JAP config
  jpa:
    database: POSTGRESQL
    show-sql: true
    properties:
      hibernate.default_schema: application

  # kafka config
  kafka:
    bootstrap-servers: localhost:9092

  # cloud config
  cloud:
    discovery:
      enabled: true


# eureka config
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

# management config
management:
  endpoints:
    web:
      exposure:
        include: heath, prometheus, info, metric
  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

google:
  appllink: https://script.google.com/macros/s/AKfycbxtuF5iqGi_MCqMzebQITUFCOOCgOyDzmrjj6EnJH82nUhCkRHoE6mrLhKDIWU08Ibs/exec
  appid: AKfycbxtuF5iqGi_MCqMzebQITUFCOOCgOyDzmrjj6EnJH82nUhCkRHoE6mrLhKDIWU08Ibs


# server config
server:
  port: 8081

viber:
  token: 5247839808f8c65e-e57e61d523fe22ed-22a29e9efa491029
  id: vFg196UcnbMF3/QlY3VFag==





